/**
 * Demo/fallback data used when backend is unreachable.
 * All objects match the @greggie/core type definitions exactly.
 */
import type { Channel, Product } from '@greggie/core';

export const DEMO_CHANNELS: Channel[] = [
  {
    id: 'demo-1',
    creator_id: 'demo-creator-1',
    title: 'Summer Fashion Drop',
    description: 'Live styling and exclusive summer fashion deals',
    category: 'Fashion',
    status: 'LIVE',
    viewer_count: 4200,
    sale_type: 'buy_now',
    thumbnail_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800&h=1200',
    stream_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=1080&h=1920',
    scheduled_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    creator_id: 'demo-creator-2',
    title: 'Tech Gadgets Unboxing',
    description: 'Unboxing the latest electronics and gadgets',
    category: 'Tech',
    status: 'LIVE',
    viewer_count: 1800,
    sale_type: 'buy_now',
    thumbnail_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&q=80&w=800&h=1200',
    stream_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&q=80&w=1080&h=1920',
    scheduled_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    creator_id: 'demo-creator-3',
    title: 'Sneaker Auction Live',
    description: 'Bid on rare and limited edition sneakers',
    category: 'Collectibles',
    status: 'LIVE',
    viewer_count: 7500,
    sale_type: 'auction',
    thumbnail_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800&h=1200',
    stream_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=1080&h=1920',
    scheduled_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    creator_id: 'demo-creator-4',
    title: 'Beauty Essentials Live',
    description: 'Skincare routines and beauty product reviews',
    category: 'Beauty',
    status: 'LIVE',
    viewer_count: 3100,
    sale_type: 'buy_now',
    thumbnail_url: 'https://images.unsplash.com/photo-1596462502278-27bf85033e5a?auto=format&fit=crop&q=80&w=800&h=1200',
    stream_url: 'https://images.unsplash.com/photo-1596462502278-27bf85033e5a?auto=format&fit=crop&q=80&w=1080&h=1920',
    scheduled_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    creator_id: 'demo-creator-5',
    title: 'Handmade Art Drop',
    description: 'Limited edition prints and original artwork',
    category: 'Art',
    status: 'RELAY',
    viewer_count: 920,
    sale_type: 'drop',
    thumbnail_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=800&h=1200',
    stream_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=1080&h=1920',
    scheduled_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_PRODUCTS: Product[] = [
  // Fashion channel
  {
    id: 'demo-p1',
    channel_id: 'demo-1',
    name: 'Silk Summer Dress',
    description: 'Lightweight silk blend, available in 4 colors',
    image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=400',
    price_cents: 8900,
    original_price_cents: 12000,
    inventory: 25,
    sale_type: 'buy_now',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-p2',
    channel_id: 'demo-1',
    name: 'Gold Chain Necklace',
    description: '18K gold plated, adjustable length',
    image_url: 'https://images.unsplash.com/photo-1515562141589-67f0d934dab6?auto=format&fit=crop&q=80&w=400',
    price_cents: 4500,
    original_price_cents: null,
    inventory: 50,
    sale_type: 'buy_now',
    is_pinned: false,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Tech channel
  {
    id: 'demo-p3',
    channel_id: 'demo-2',
    name: 'Wireless Earbuds Pro',
    description: 'ANC, 36hr battery, IPX5 waterproof',
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=400',
    price_cents: 12900,
    original_price_cents: 15900,
    inventory: 10,
    sale_type: 'auction',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-p4',
    channel_id: 'demo-2',
    name: 'Smart Watch Ultra',
    description: 'AMOLED display, health tracking, 5-day battery',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=400',
    price_cents: 19900,
    original_price_cents: null,
    inventory: 15,
    sale_type: 'buy_now',
    is_pinned: false,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Sneaker channel
  {
    id: 'demo-p5',
    channel_id: 'demo-3',
    name: 'Air Jordan Retro 4',
    description: 'Deadstock, size 10, original box',
    image_url: 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&q=80&w=400',
    price_cents: 25000,
    original_price_cents: null,
    inventory: 1,
    sale_type: 'auction',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-p6',
    channel_id: 'demo-3',
    name: 'Yeezy Boost 350',
    description: 'Brand new, size 11, limited colorway',
    image_url: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&q=80&w=400',
    price_cents: 22000,
    original_price_cents: null,
    inventory: 1,
    sale_type: 'auction',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Beauty channel
  {
    id: 'demo-p7',
    channel_id: 'demo-4',
    name: 'Hydrating Serum Set',
    description: 'Vitamin C + Hyaluronic acid, 3-pack',
    image_url: 'https://images.unsplash.com/photo-1512496115841-3450283723be?auto=format&fit=crop&q=80&w=400',
    price_cents: 3400,
    original_price_cents: 4200,
    inventory: 100,
    sale_type: 'buy_now',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Art channel
  {
    id: 'demo-p8',
    channel_id: 'demo-5',
    name: 'Signed Art Print',
    description: 'Limited edition 1/50, numbered and signed',
    image_url: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&q=80&w=400',
    price_cents: 15000,
    original_price_cents: null,
    inventory: 1,
    sale_type: 'drop',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Creator studio demo data
export const DEMO_CREATOR_CHANNEL: Channel = {
  id: 'creator-demo-1',
  creator_id: 'me',
  title: 'My Live Shop',
  description: 'Your personal live shopping channel',
  category: 'Fashion',
  status: 'LIVE',
  viewer_count: 0,
  sale_type: 'buy_now',
  thumbnail_url: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&q=80&w=800&h=1200',
  stream_url: '',
  scheduled_at: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_CREATOR_PRODUCTS: Product[] = [
  {
    id: 'cp-1',
    channel_id: 'creator-demo-1',
    name: 'Handmade Bracelet Set',
    description: 'Set of 3, hypoallergenic materials',
    image_url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&q=80&w=400',
    price_cents: 3500,
    original_price_cents: null,
    inventory: 30,
    sale_type: 'buy_now',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cp-2',
    channel_id: 'creator-demo-1',
    name: 'Vintage Sunglasses',
    description: 'UV400 protection, retro cat-eye frame',
    image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=400',
    price_cents: 5900,
    original_price_cents: 7500,
    inventory: 12,
    sale_type: 'buy_now',
    is_pinned: false,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cp-3',
    channel_id: 'creator-demo-1',
    name: 'Signed Art Print',
    description: 'Original artwork, certificate of authenticity',
    image_url: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&q=80&w=400',
    price_cents: 15000,
    original_price_cents: null,
    inventory: 1,
    sale_type: 'auction',
    is_pinned: true,
    auction_end_at: null,
    drop_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
